sudo: false
cache: pip

language: python

python:
  - "2.7"

env:
  - VERSION="9.0" ODOO_REPO="odoo/odoo"
  - VERSION="9.0" UNIT_TEST="1" INCLUDE="purchase_request"

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-serial
      - python-yaml
      - node-less

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install unicodecsv unidecode ofxparse

script:
  - travis_run_tests

after_success:
  - coveralls
  
